### ISSUE TITLE
Cannot generate thumbnail for videos

### ISSUE THREAD

**Issue by Linspirit98** [justsoft/video_thumbnail#100]
couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11832
"Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used.,
NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x282ee3960 {Error
Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}}

Any suggestion why this might happen? my ffmpegCommand is null. 
More info:
dart 2.10.2
flutter 2.16
iphone 11
ios 14.6

**Comment by justsoft** [comment]
Please check out the new 0.5.0 version. Thanks.

**Comment by praveenjaiswal16** [comment]
version is 0.5.0 but when the app is first time installed app and selects more than 200 images the issue is occured
