### ISSUE TITLE
[iOS] Unable to generate thumbnail 

### ISSUE THREAD

**Issue by tronghuy5555** [justsoft/video_thumbnail#104]
Hi everyone,
I am unable to generate thumbnail in some videos
Android works fine
Log below:

`couldn't generate thumbnail, error:Error Domain=AVFoundationErrorDomain Code=-11832 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media cannot be used., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x600003e93a80 {Error Domain=NSOSStatusErrorDomain Code=-12431 "(null)"}}`

Example link: [https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-mp4-file.mp4](url)
Device: iOS simulator
Flutter version: 2.5.1

**Comment by justsoft** [comment]
The video isn't able to play on iOS device, seems the video format isn't compatible with iPhone at least based on my test.
