### ISSUE TITLE
error: unreported exception IOException; must be caught or declared to be thrown                 retriever.release();

### ISSUE THREAD

**Issue by itEstimators** [justsoft/video_thumbnail#111]

**Comment by KrunalNathani** [comment]
unreported exception IOException; must be caught or declared to be thrown retriever.release() BELOW ANDROID 10 VERSION THIS ERROR PRODUCE BUT ANDROID 11 & 12 VERSION IN COMPLETELY WORKING

**Comment by hadi20sa** [comment]
I am getting the same error

**Comment by nkesarwani7** [comment]
same error:

/Users/mac/.pub-cache/hosted/pub.dartlang.org/video_thumbnail-0.5.0/android/src/main/java/xyz/justsoft/video_thumbnail/VideoThumbnailPlugin.java:253: error: unreported exception IOException; must be caught or declared to be thrown
                retriever.release()

**Comment by AnasSafi** [comment]
same error on flutter v3.0.4

**Comment by zzterrozz** [comment]
same here, anyone found a solution or workaround?

**Comment by justsoft** [comment]
I will publish a new version soon, please try that.
Also as I commented on an other issue, please take care the URL and the file full path of the writing file. Make sure the full path is valid for iOS/Android and the App has sufficient permissions to create, read and write on it.

**Comment by c0c4i** [comment]
I tried this new version 0.5.2 but I still have this problem running my app on android.
Here is my error on debug console.
```
/development/flutter/.pub-cache/hosted/pub.dartlang.org/video_thumbnail-0.5.2/android/src/main/java/xyz/justsoft/video_thumbnail/VideoThumbnailPlugin.java:253: error: unreported exception IOException; must be caught or declared to be thrown retriever.release();
```

**Comment by NiuXiaoGuang** [comment]
Flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/video_thumbnail-0.5.2/android/src/main/java/xyz/justsoft/video_thumbnail/VideoThumbnailPlugin.java:253: 错误: 未报告的异常错误java.io.IOException; 必须对其进行捕获或声明以便抛出
                retriever.release();

问题还是存在
