### ISSUE TITLE
[0.5.1] IOException catch error when building on Android

### ISSUE THREAD

**Issue by WatchDogsDev** [justsoft/video_thumbnail#117]
Hi, I updated the package to 0.5.1 recently. When I tried to build the app, I got error below:

```
/flutter/.pub-cache/hosted/pub.dartlang.org/video_thumbnail-0.5.1/android/src/main/java/xyz/justsoft/video_thumbnail/VideoThumbnailPlugin.java:256: error: exception IOException is never thrown in body of corresponding try statement
            } catch (IOException ex) {
              ^
1 error
FAILURE: Build failed with an exception.
```

**Comment by justsoft** [comment]
I am building the example App by Flutter 3.0.5 now on Windows, it was succeeded by Flutter 2.10.5 on Mac.

**Comment by justsoft** [comment]
It does cause warning on latest Android Studio, reverted the change.
Will publish the package soon, thanks.
