### ISSUE TITLE
 retriever.release(); , Not working

### ISSUE THREAD

**Issue by Iamdheeraj22** [justsoft/video_thumbnail#125]
E:\flutter\.pub-cache\hosted\pub.dartlang.org\video_thumbnail-0.5.2\android\src\main\java\xyz\justsoft\video_thumbnail\VideoThumbnailPlugin.java:253: error: unreported exception IOException; must be caught or declared to be thrown
                retriever.release();

![issue](https://user-images.githubusercontent.com/59793386/185295798-f0ed7fd2-3c33-4941-9d76-8d2e8089d5a4.PNG)

**Comment by Kanwarpalsingh1986** [comment]
Same issue here form last 1 month and no resolution, please help

**Comment by sonnts996** [comment]
Versions 0.5.0 and 0.5.2 have the same error. I've quick looked at the code between versions, it seems 5.0.1 has fixed the above error. it works with my code.

**Comment by nawafAlkhadidi** [comment]
Same issue

**Comment by Helocominc** [comment]
Any fix yet

**Comment by eduardobursa** [comment]
I Had the same issue. The downgrade proposed by @sonnts996 solved the problem for now.
