### ISSUE TITLE
No implementation found for method file on channel video_thumbnail

### ISSUE THREAD

**Issue by atha-cyanberg** [justsoft/video_thumbnail#13]
When I am going to generate firebase storage file thumbnail, it showing a exception: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method file on channel video_thumbnail)

String fileURL = "https://firebasestorage.googleapis.com/v0/b/hollistic-living-test.appspot.com/o/chatFiles%2F1579869657089_kv.mp4?alt=media&token=ff204023-27c7-4922-be6b-6a702f508763";
    String thumbnailUrl = await VideoThumbnail.thumbnailFile(
      video: fileURL,
      thumbnailPath: null,
      imageFormat: ImageFormat.JPEG,
      maxHeight: 64,
      quality: 75,
    );
    print(thumbnailUrl);

**Comment by justsoft** [comment]
Make sure the video is playable on your system.
You may need install some codecs if you are on Android.

**Comment by atha-cyanberg** [comment]
My video is playable, and I am using android emulater latest version and video_thumbnail: ^0.2.0, sdk: ">=2.0.0-dev.68.0 <3.0.0", but not working, please help me what I need to change in codecs!

**Comment by justsoft** [comment]
Have you tried on a real phone? If still doesn't work, after install something like MX Player Codec & MX player, then try again.

**Comment by brenno951** [comment]
same issue

**Comment by sc4v3ng3r** [comment]
Same issue on iOS using a real device.

**Comment by justsoft** [comment]
Have you tried to move the video to another HTTPS Web server and using a simple URL?

**Comment by AresVampire** [comment]
I am experiencing the same issue. Maybe after upgrade version to 0.2.0

**Comment by AresVampire** [comment]
I think it is related to file name or path - like %2F is causing problem

**Comment by AresVampire** [comment]
It is related to Utf8 string in your path.
So before using it, you need to decode the url from Utf8. Then it surely works.
    `URLDecoder.decode(video, "UTF-8")`

**Comment by justsoft** [comment]
> It is related to Utf8 string in your path.
> So before using it, you need to decode the url from Utf8. Then it surely works.
> `URLDecoder.decode(video, "UTF-8")`

I bet you have found the right solution.
Thank you very much.

**Comment by devDonald** [comment]
@justsoft  Please I can't figure how to get the UrLdecoder class

**Comment by justsoft** [comment]
@devDonald You might try this https://api.flutter.dev/flutter/dart-core/Uri/encodeFull.html, or find an URL encode package.
