### ISSUE TITLE
Not working on ios

### ISSUE THREAD

**Issue by DeepakSinghaniya** [justsoft/video_thumbnail#15]
```
          final thumbnailPath = await VideoThumbnail.thumbnailFile(
           video: widget.videoPath,
            imageFormat: ImageFormat.JPEG,
            maxWidth: 128,
            timeMs: (index * (widget.videoDuration / 10.0)).toInt(),
            quality: 25);
```

Not working on ios

**Comment by Ahmadre** [comment]
try with thumbnailData and wrap your data into: `Image.memory(data);`. If you need a builder for that just use: `FutureBuilder<UInt8List>`

**Comment by justsoft** [comment]
Please take a look the example, you might forget to grant read and write permissions for iOS storage. Or as Ahmadre's suggestion, just create the thumbnail in memory.
