### ISSUE TITLE
Error running pod install

### ISSUE THREAD

**Issue by what2003** [justsoft/video_thumbnail#2]
It gets "Error running pod install" everytime in IOS when I put vidieo_thumbnail in pubspec.yaml. 
Nothing wrong with Android though. 
Very useful plugin, hop it gets fixed soon.
Thank you !

**Comment by what2003** [comment]
camera_utils gets the same problem, I don't know, maybe it is flutter's bug?

**Comment by justsoft** [comment]
Sorry I don't have an extra MacOSX environment to try everything from scratch.

Any potential internet connection issue?
It depends on Google  WebP library for supporting WebP format. Try to install webp manually:

> brew install webp

Or If you don't need WebP format for iOS, you can just simply remove that part of code from the plugin.
