### ISSUE TITLE
ThumbnailPlugin: setDataSource prints the video url unsafe for disabling external access

### ISSUE THREAD

**Issue by ArjunNagraj** [justsoft/video_thumbnail#20]
The setDataSource  method....prints the video url.
This is unsafe since anyone can now get access to the video url and download the video.
This needs to be commented or a parameter set to display this Print.

**Comment by justsoft** [comment]
Thanks for pointing this out, updated.

**Comment by ArjunNagraj** [comment]
> Thanks for pointing this out, updated.

No worries. Thanks for the plugin :). Cheers.
