### ISSUE TITLE
iOS Live Photo "videos" are returning null on thumbnailData

### ISSUE THREAD

**Issue by aawhitfield** [justsoft/video_thumbnail#21]
If I select a "live photo" from iOS, it is showing as a .MOV file. If I pass that "video" file to the plugin with :
`FutureBuilder(
                        future: VideoThumbnail.thumbnailData(
                          video: widget.file.path,
                          imageFormat: ImageFormat.JPEG,
                          maxHeight: 100,
                          maxWidth: 100,
                          quality: 100,
                        ),
                        builder: (BuildContext context,
                            AsyncSnapshot<Uint8List> snapshot) {
                          if (snapshot.connectionState ==
                              ConnectionState.waiting)
                            return PlatformCircularProgressIndicator();
                          else
                            return Image.memory(snapshot.data);
                        },
                      )`

the future returns null in snapshot.data.

**Comment by justsoft** [comment]
@aawhitfield How did you pick the live photo? The Image_Picker seems don't support pick the .mov file.
I have to upload the .mov (live photo) file to a web site first, if you have an easier way please let me know.
Confirmed the issue happens on iOS, works on Android. I will try to fix it.

Thanks

**Comment by aawhitfield** [comment]
I'm using the multi image picker plug in. Thanks!

**Comment by justsoft** [comment]
@aawhitfield I found it works under the Simulator all the time, had 1/4 chances worked on my iOS 13.4.1's device.

**Comment by scofield-hello** [comment]
same problem

**Comment by justsoft** [comment]
Verified again:
1) The multi_image_picker doesn't return the .mov file, but .HEIC
2) The live photo can be exported by Mac photos as .heic and .mov file, but the .mov file is HEVC encoded.

So far I have no idea to fix this issue.
