### ISSUE TITLE
有没有比较快的方式拿到一个视频的的每秒缩略图

### ISSUE THREAD

**Issue by JamesBondPc** [justsoft/video_thumbnail#24]
有没有比较快的方式拿到一个视频的的每秒缩略图

**Comment by justsoft** [comment]
Plenty of ways, but how fast is faster?

**Comment by JamesBondPc** [comment]
It can be within 1 second, and it can be loaded when the user slides




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John Zhong"<notifications@github.com&gt;; 
发送时间: 2020年4月21日(星期二) 下午4:26
收件人: "justsoft/video_thumbnail"<video_thumbnail@noreply.github.com&gt;; 
抄送: "James Bond"<710774798@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [justsoft/video_thumbnail] 有没有比较快的方式拿到一个视频的的每秒缩略图 (#24)





 
Plenty of ways, but how fast is faster?

**Comment by JamesBondPc** [comment]
like VN



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "John Zhong"<notifications@github.com&gt;; 
发送时间: 2020年4月21日(星期二) 下午4:26
收件人: "justsoft/video_thumbnail"<video_thumbnail@noreply.github.com&gt;; 
抄送: "James Bond"<710774798@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [justsoft/video_thumbnail] 有没有比较快的方式拿到一个视频的的每秒缩略图 (#24)





 
Plenty of ways, but how fast is faster?

**Comment by justsoft** [comment]
MI6 may know :)

**Comment by justsoft** [comment]
Just kidding. You might try:
- Probably generating thumbnails on a server is a better choice.
- If really like to do it on user's device, give a try for this plugin with the 'timeMs' in a loop for a video

**Comment by dodatw** [comment]
Hi Justsoft,

on iOS, is it possible integrate generatecgimagesasynchronously ?
https://developer.apple.com/documentation/avfoundation/avassetimagegenerator/1388100-generatecgimagesasynchronously

**Comment by justsoft** [comment]
@dodatw Thanks for the suggestion, it is using `dispatch_async` now, but your suggestion should make the code simpler.
