### ISSUE TITLE
MissingPluginException (MissingPluginException(No implementation found for method data on channel video_thumbnail))

### ISSUE THREAD

**Issue by JamesBondPc** [justsoft/video_thumbnail#26]
MissingPluginException (MissingPluginException(No implementation found for method data on channel video_thumbnail))

**Comment by Hyottoko** [comment]
I just encountered this error using the plug-in

**Comment by Hyottoko** [comment]
I also encountered this problem just using this plugin package

**Comment by d-apps** [comment]
Same here.

Method Channel can't find 'data' method inside the kotlin file. It's like it isn't registered or something.

![image](https://user-images.githubusercontent.com/20110433/80155654-891b1c80-8598-11ea-871a-5395c508b220.png)

**Comment by justsoft** [comment]
Have you granted the permission to access internet for your App?

**Comment by d-apps** [comment]
> Have you granted the permission to access internet for your App?

Yes.
Any solution? You closed the issue...

**Comment by JamesBondPc** [comment]
Of course it ’s open. Does it have anything to do with this?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "D-Apps"<notifications@github.com&gt;; 
发送时间: 2020年4月24日(星期五) 上午9:56
收件人: "justsoft/video_thumbnail"<video_thumbnail@noreply.github.com&gt;; 
抄送: "James Bond"<710774798@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [justsoft/video_thumbnail] MissingPluginException (MissingPluginException(No implementation found for method data on channel video_thumbnail)) (#26)





  
Have you granted the permission to access internet for your App?
  
Yes.
 Any solution? You closed the issue...

**Comment by justsoft** [comment]
@d-apps Because it is something related with your environment or your App, nothing needs to be changed on the plugin side.
Please play with the example comes with this plugin.
@JamesBondPc @d-apps Try with a brand new project or start from the example comes with this plugin. Also make sure the video is playable on your devices.

**Comment by sgehrman** [comment]
same issue.  No idea how to get around this.
