### ISSUE TITLE
Failed to connect to device

### ISSUE THREAD

**Issue by tumlaygit** [justsoft/video_thumbnail#28]
When I add this plugin, I can't debug on IPad. (I can debug if I remove it from project)
It showed: Error connecting to the service protocol: failed to connect to http://127.0.0.1 ...
I use:
Flutter channel stable, v1.12.13+hostfix.8, on Mac OS X 10.15.4
Android SDK version 28.0.3
Xcode 11.4

**Comment by justsoft** [comment]
Try:
1. Clean the current build
```
flutter clean
```
2. Do pod update
```
cd ios
rm -fr Podfile.lock Pods
pod install --repo-update
```
