### ISSUE TITLE
Support .m3u8 format video ?

### ISSUE THREAD

**Issue by z234009184** [justsoft/video_thumbnail#36]
Do you support video in. M3u8 format?

**Comment by huxaiphaer** [comment]
@z234009184 did it work for you , am also facing the same issue ?

**Comment by justsoft** [comment]
It should be able to generate any playable video, try it by yourself please.
If it doesn't work, make sure the video can be played by built-in video play or the WEB browser.

**Comment by justsoft** [comment]
I have verified this plugin wouldn't be able to generate the thumbnails from .m3u8.
But you can simple read the .m3u8 then find out the .ts, then generate the thumbnail from the .ts file.

**Comment by rekonvald** [comment]
Hi! Have you found solution? I implemented 

> read the .m3u8 then find out the .ts, then generate the thumbnail from the .ts file.

It works for Android, but not for ios
