### ISSUE TITLE
set header for url video

### ISSUE THREAD

**Issue by mmrmmr** [justsoft/video_thumbnail#41]
How can I set the header video link to the server to check the user token?
please help me (:

**Comment by ali-tafakkori** [comment]
+1

**Comment by justsoft** [comment]
You might find a better place to ask this question, one basic way to archive your goal is passing additional query string, something like https://<the_video_url>?toke=<this_token>.

**Comment by abehbatre** [comment]
please add header ..

my company need to add headers with referral to access assets .. :"))

**Comment by justsoft** [comment]
Please check out the new 0.5.0 version. Thanks.
