### ISSUE TITLE
MissingPluginException(No implementation found for method file on channel video_thumbnail)

### ISSUE THREAD

**Issue by devanshkaria88** [justsoft/video_thumbnail#42]
I have a similar issue. I am trying to get a thumbnail from a video picked using the flutter_file_picker plugin and I am getting this issue.

`<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.FLASHLIGHT" />
`

This is my AndroidManifest.xml permission part. and I am using this plugin in a similar way that @atheist1 used.

Looking for your response as quickly as possible as this is for production purposes.

Edit: This issue is only found in devices with Andoird 9 or below. and the flutter version that I am using is 1.20.0

**Comment by FrostArcher** [comment]
I am getting the same issue, plus in ios 14 the thumbnail comes blank. please fix

**Comment by NaorShmueli** [comment]
hi, i get this error below at creating with VideoThumbnail.thumbnailData from video path at getTemporaryDirectory() (path provider).
the video is an mp4 file that recorder by a camera.

Exception has occurred.
MissingPluginException (MissingPluginException(No implementation found for method data on channel video_thumbnail))

final reqMap = <String, dynamic>{
      'video': "/data/user/0/com.example.Webet/cache/Videos/1603652090953.mp4," (path to file)
      'format': ImageFormat.JPEG
      'maxh': maxHeight ?? 0,
      'maxw': maxWidth ?? 0,
      'timeMs': timeMs ?? 0,
      'quality': quality ?? 10
    };

**Comment by zxhwyp** [comment]
i get this error, but  when i test url from  demo in plugin (this: https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4) the error is gone. so i think maybe the path make this error. in the end, i resolve the error by modify the value of video path passing to video param

**Comment by justsoft** [comment]
Thanks for zxhwyp
