### ISSUE TITLE
Invalid plugin specification video_thumbnail

### ISSUE THREAD

**Issue by barees63** [justsoft/video_thumbnail#44]
Hi there,

I just started getting this error on "pub get" today:

Invalid plugin specification video_thumbnail.
Cannot find the `flutter.plugin.platforms` key in the `pubspec.yaml` file

I've tried older versions and all of them are giving me the same error, everything works if I remove the package.

[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-NZ)
    • Flutter version 1.23.0-18.1.pre at /Users/barees/flutter
    • Framework revision 198df796aa (13 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/barees/android-sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/barees/android-sdk
    • ANDROID_SDK_ROOT = /Users/barees/android-sdk
    • Java binary at: /Users/barees/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6821437/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0.rc.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/barees/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6821437/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.3)
    • IntelliJ at /Users/barees/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin installed
    • Dart plugin version 202.7319.5

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.27 beta

• No issues found!

**Comment by barees63** [comment]
FWIW, if I fork it and change the plugin section back to:

plugin:
    androidPackage: xyz.justsoft.video_thumbnain
    pluginClass: VideoThumbnailPlugin


Then it works.

**Comment by a-href** [comment]
The same error  about

**Comment by gulmensedat** [comment]
> xyz.justsoft.video_thumbnain

not work :(

**Comment by vertify-mldev1** [comment]
This will work as well:
```
plugin:
    platforms:
      android:
        package: xyz.justsoft.video_thumbnail
        pluginClass: VideoThumbnailPlugin
      ios:
        pluginClass: VideoThumbnailPlugin
```

**Comment by justsoft** [comment]
Thanks for all. Please try the latest 0.2.4.

**Comment by gulmensedat** [comment]
> plugin:
>     platforms:
>       android:
>         package: xyz.justsoft.video_thumbnail
>         pluginClass: VideoThumbnailPlugin
>       ios:
>         pluginClass: VideoThumbnailPlugin

flutter:
  plugin:
    platforms:
        androidPackage: xyz.justsoft.video_thumbnail
        pluginClass: VideoThumbnailPlugin

new version and it worked with code. good work
