### ISSUE TITLE
Unable to create a thumbnail for video with .MOV extension on Android device while it is working on iPhone. Any help will be appreciated. 

### ISSUE THREAD

**Issue by BabarJan90** [justsoft/video_thumbnail#47]

**Comment by justsoft** [comment]
Please take a look the existing issues. The most possible reason causes this issue is your Android device doesn't have the appropriate decoder. Have you tried to play this .MOV video on the device directly? Try to install some decoder if it failed to play. Try this package again after installed the appropriate decoder.

**Comment by BabarJan90** [comment]
@justsoft Yes, it is playable this .MOV file.

**Comment by justsoft** [comment]
Have you tried on a different device?
Can you put the video somewhere I and other can try?

**Comment by brunoda6** [comment]
Hi did someone have found a solution for this issue? i have the same problem with the .mov file it works well on ios on android it crashes.

i have tested on 2 different android phones both can play mov files without problem.

this is the error that i am getting:
`MissingPluginException (MissingPluginException(No implementation found for method file on channel plugins.justsoft.xyz/video_thumbnail))`

On Debug console:
`W/System.err(14769): java.lang.RuntimeException: setDataSource failed: status = 0x80000000
W/System.err(14769): 	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
W/System.err(14769): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:97)
W/System.err(14769): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.createVideoThumbnail(VideoThumbnailPlugin.java:203)
W/System.err(14769): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.buildThumbnailData(VideoThumbnailPlugin.java:114)
W/System.err(14769): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.buildThumbnailFile(VideoThumbnailPlugin.java:130)
W/System.err(14769): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.access$000(VideoThumbnailPlugin.java:27)
W/System.err(14769): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin$1.run(VideoThumbnailPlugin.java:71)
W/System.err(14769): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err(14769): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err(14769): 	at java.lang.Thread.run(Thread.java:761)
`
Note: it works with mp4 files i tried your example video  

ty

**Comment by justsoft** [comment]
Don't know the reason, try to convert this video to another format.
