### ISSUE TITLE
is this bug?

### ISSUE THREAD

**Issue by gmae199boy** [justsoft/video_thumbnail#51]
<img width="1155" alt="스크린샷 2020-12-09 오전 9 09 32" src="https://user-images.githubusercontent.com/34611716/101556555-7ad22180-39fe-11eb-90ae-9c76ba30eac1.png">

<img width="1079" alt="스크린샷 2020-12-09 오전 9 26 06" src="https://user-images.githubusercontent.com/34611716/101557596-a9e99280-3a00-11eb-9155-36a9e76b0e32.png">

When I try to use the library, I get this error.
`        _thumbnailImage.add(await VideoThumbnail.thumbnailData(
          video: result.paths[i],
          imageFormat: ImageFormat.PNG,
          maxWidth:
              128, // specify the width of the thumbnail, let the height auto-scaled to keep the source aspect ratio
          quality: 25,
        ));
`

I don't think it's another problem because the error comes out regardless of the platform.
This is the code I used exactly as shown in the example.

**Comment by gmae199boy** [comment]
> Sorry, I made a typo in my last checking. Please try the updated version.

Sorry. I upgraded the version, but it has the same bug.

**Comment by justsoft** [comment]
Have you tried with other video format? Is the video or URL can be played by the WEB browser or the build in video player?
