### ISSUE TITLE
iOS 14.2 Device PlatformException(IO Error, Failed to write data to file, null, null)

### ISSUE THREAD

**Issue by squallml** [justsoft/video_thumbnail#52]
iOS 14.2 Device
`final thumbnailPath = await VideoThumbnail.thumbnailFile(
            video: file,
            thumbnailPath: (await getTemporaryDirectory()).path,
            imageFormat: ImageFormat.JPEG,
            maxHeight: 300,
            quality: 75,
          );`
bug: `flutter: PlatformException(IO Error, Failed to write data to file, null, null)`

but, iOS 14.2 Simulators is ok.

**Comment by justsoft** [comment]
Please try the v0.2.5+1

**Comment by Wiki1991** [comment]
iOS14.4.2
I used v0.2.5+1.but still have the same problem.The cache directory I use is `await getApplactionDocumentsDirectory().path`

**Comment by justsoft** [comment]
1) Please use the latest version of the package
2) Try the `await getTemporaryDirectory()` instead of the `getApplicationDocumentsDirectory()`

**Comment by EjazAmir** [comment]
I'm using v0.2.5+1 and still getting this error:
flutter: PlatformException(IO Error, Failed to write data to file, null, null)

**Comment by justsoft** [comment]
Try to use the `thumbnailData` instead of writing the thumbnail data into a file.
