### ISSUE TITLE
i got error in android 11

### ISSUE THREAD

**Issue by twin-eng** [justsoft/video_thumbnail#53]
![i1](https://user-images.githubusercontent.com/58139175/105444876-b108ef00-5c94-11eb-99ac-9091e8c77c9e.JPG)
![adada](https://user-images.githubusercontent.com/58139175/105444880-b2d2b280-5c94-11eb-9154-481ac2271e6c.JPG)

**Comment by twin-eng** [comment]
my video file location 
 /storage/emulated/0/Android/data/com.mu/files/video/

**Comment by justsoft** [comment]
The `thumbnailData` returns `Uint8List`, and the `thumbnailFile` returns `String`
Make sure the video file can be read, and the destination folder can be written if you would like to use the `thumbnailFile`.

**Comment by twin-eng** [comment]
> The `thumbnailData` returns `Uint8List`, and the `thumbnailFile` returns `String`
> Make sure the video file can be read, and the destination folder can be written if you would like to use the `thumbnailFile`.

**Comment by twin-eng** [comment]
> The `thumbnailData` returns `Uint8List`, and the `thumbnailFile` returns `String`
> Make sure the video file can be read, and the destination folder can be written if you would like to use the `thumbnailFile`.

thank you your response, it working another android version. i use thumbnailFile file from temporary directory any idea.

**Comment by justsoft** [comment]
@twin-eng If you need to generate the thumbnail file in the temporary folder, you can specify the destination folder by giving `thumbnailPath` a value, like I did in my example:
```
final fileName = await VideoThumbnail.thumbnailFile(
  video: "https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4",
  thumbnailPath: (await getTemporaryDirectory()).path,
  imageFormat: ImageFormat.WEBP,
  maxHeight: 64, // specify the height of the thumbnail, let the width auto-scaled to keep the source aspect ratio
  quality: 75,
);
```
