### ISSUE TITLE
android 11 : setDataSource java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by mrtian** [justsoft/video_thumbnail#54]
error code: 
java.lang.IllegalArgumentException
W/System.err(12398): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:81)
W/System.err(12398): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.createVideoThumbnail(VideoThumbnailPlugin.java:203)
W/System.err(12398): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.buildThumbnailData(VideoThumbnailPlugin.java:116)

dart side:
await VideoThumbnail.thumbnailData(
        imageFormat: ImageFormat.JPEG,
        video: path, // "file:///data/......../a.mp4"
        timeMs: (eachPart * i).toInt(),
        quality: widget.quality,
      );

**Comment by justsoft** [comment]
It doesn't support file based URL. For local resources please use a regular file path.
