### ISSUE TITLE
Missing plugin exception

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [justsoft/video_thumbnail#55]
Unhandled Exception: MissingPluginException(No implementation found for method data on channel video_thumbnail)

i am trying to fetch the thumbnail from video by url and i am getting this error everytime i clean the build pub get upgrade tried everything but not getting any solution

**Comment by justsoft** [comment]
Have you tried another URL? Try an URL encoded URL?
Is the video playable on your device?
Does the App have permissions to access the internet?

**Comment by Stitch-Taotao** [comment]
Same issue
