### ISSUE TITLE
MissingPluginException

### ISSUE THREAD

**Issue by BhavyKoshti9spl** [justsoft/video_thumbnail#56]
E/MediaMetadataRetrieverJNI(16929): getFrameAtTime: videoFrame is a NULL pointer
E/flutter (16929): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method data on channel video_thumbnail)
 #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
 <asynchronous suspension>
 #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
 #2      VideoThumbnail.thumbnailData (package:video_thumbnail/video_thumbnail.dart:67:27)
 #3      FeedScreenState.getVideoView (package:turf_talk/ui/home_and_associate_screens/feed_screen.dart:1034:22)

**Comment by justsoft** [comment]
Did you try to play the video by other tools or load it by the builtin browser?

**Comment by laowangDemon** [comment]
I have the same question

**Comment by HongZhiQing** [comment]
I have the same question
