### ISSUE TITLE
MissingPluginException(No implementation found for method data on channel video_thumbnail)

### ISSUE THREAD

**Issue by ajosecueto** [justsoft/video_thumbnail#59]
ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method data on channel video_thumbnail)
E/flutter ( 9427): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter ( 9427): <asynchronous suspension>
E/flutter ( 9427): #1      VideoThumbnail.thumbnailData (package:video_thumbnail/video_thumbnail.dart:67:12)
E/flutter ( 9427): <asynchronous suspension>
E/flutter ( 9427): #2      _UploadClipState.loadThumb (package:proyectBlumer/screens/upload_post/upload_clip.dart:43:5)
E/flutter ( 9427): <asynchronous suspension>
E/flutter ( 9427):

**Comment by isaacfi** [comment]
Hi @ajosecueto,

Are you using openJDK 8? I had to go back to Java JDK 8 due to this issue. This seems to happen for some more than 10 seconds videos.

BR.

**Comment by isaacfi** [comment]
Sorry about my comment it still happen in some videos no matter if you use Java JDK or OpenJDK

**Comment by DevKhalyd** [comment]
Hi, I have the same issue. Did you find the answer? Thanks

**Comment by DevKhalyd** [comment]
I fix that error just adding ` thumbnailPath: (await getTemporaryDirectory()).path` to my method 👍

**Comment by justsoft** [comment]
Thanks @DevKhalyd

**Comment by justsoft** [comment]
Please check out the new 0.5.0 version. Thanks.
