### ISSUE TITLE
iOS only - FileSystemException was thrown resolving an image codec

### ISSUE THREAD

**Issue by fiixed** [justsoft/video_thumbnail#6]
Hi,

I am trying to save (and retrieve) the thumbnail image from the same folder as the video.

When I try the following, the app crashes with no deb messages, it just closes the app with no errors:

```
Future<File> getThumbnail(String videoPath) async {
    final thumbnail = await VideoThumbnail.thumbnailFile(
        video: videoPath,
        thumbnailPath: null,
        imageFormat: ImageFormat.PNG,
        maxHeightOrWidth: _size,
        timeMs: _timeMs,
        quality: _quality);
    return File(thumbnail);
  }
```

When I try this instead, it works and the thumbnail is saved:

```
Future<File> getThumbnail(String videoPath) async {
    final thumbnail = await VideoThumbnail.thumbnailFile(
        video: videoPath,
        thumbnailPath: videoPath.split('.')[0]+ '.png',
        imageFormat: ImageFormat.PNG,
        maxHeightOrWidth: _size,
        timeMs: _timeMs,
        quality: _quality);
    return File(thumbnail);
  }
```
But if I restart the app, I get the following FileSystemException error:

```
════════ Exception caught by image resource service ════════════════════════════
The following FileSystemException was thrown resolving an image codec:
Cannot open file, path = '/var/mobile/Containers/Data/Application/E0C7FD38-BBD6-41D8-83B3-51669FFF451A/Documents/Movies/video_diary/1574955658841.png' (OS Error: No such file or directory, errno = 2)

When the exception was thrown, this was the stack
#0      _File.open.<anonymous closure>  (dart:io/file_impl.dart:366:9)
(elided 13 frames from package dart:async)
Path: /var/mobile/Containers/Data/Application/E0C7FD38-BBD6-41D8-83B3-51669FFF451A/Documents/Movies/video_diary/1574955658841.png
```
I have checked the path and that is the correct path (where the thumbnail was saved).  Why is iOS having trouble retrieving it?  I'm using iOS 13.2.2.  On Android there are no issues.

**Comment by fiixed** [comment]
I should add that when I remove the app from memory, I can retrieve the image file.  
I'm saving the image using SQflite, so its only when I restart app from scratch I couldn't locate the image file again.

**Comment by fiixed** [comment]
Also, when I use thumbnailPath: videoPath.split('.')[0]+ '.png' it breaks.  So I would rather get thumbnailPath: null working on iOS.

**Comment by justsoft** [comment]
Have you added sufficient permissions for the iOS App?
Have you tried to use the path_provider plugin to get the right folder to save the thumbnail files?

**Comment by fiixed** [comment]
Yes I'm using path provider.  What permissions are needed for iOS?  I couldn't find any?

**Comment by justsoft** [comment]
At very least following permissions are needed for storing files on mobile device ( I use the permission_handler plugin as an example ):
For Android needs following permissions in manifest: 
```
<uses-permission android:name="android.permission.INTERNET"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
```
And permissions:
```
PermissionGroup.camera,
PermissionGroup.storage,
```

For iOS permissions
```
PermissionGroup.camera,
PermissionGroup.mediaLibrary,
PermissionGroup.photos,
```
Also the best place to store App files is the 'Documents'.

**Comment by haoqiangyu** [comment]
This problem still exists. 

flutter doctor :
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.4 18E226, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/mac/development/flutter
    • Framework revision 27321ebbad (13 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode10.3.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.1.2
    • Dart plugin version 191.8423
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • iPhone6Plus• iOS 12.1

Plugin version: 
video_thumbnail: ^0.1.7
code:
String thumbPath = await VideoThumbnail.thumbnailFile(
      video: video.path,
      imageFormat: ImageFormat.PNG,
      maxHeightOrWidth: 100,
      quality: 50,
    );

It works fine on Android and generates a crash on IOS. I have added the permissions you listed, so the reason for this may not be a permission issue. Thank you for your contribution and attention!

**Comment by shihabmi7** [comment]
I faced the same issue in ios. 

Fix by using 

`final Directory _appDocDir = await getApplicationDocumentsDirectory();`

Previously used 

`final Directory _appDocDir = await getApplicationSupportDirectory();`
