### ISSUE TITLE
Can't generate thumbnail from m3u8 format

### ISSUE THREAD

**Issue by rekonvald** [justsoft/video_thumbnail#64]
Hi!

Unfortunately, can't generate thumbnail from video url in such format.
Issue occurs on IOS

**Comment by justsoft** [comment]
I will add this feature into the TODO list, thanks

**Comment by rekonvald** [comment]
Thanks, could you please tell me when I can hope it will be implemented?)

**Comment by justsoft** [comment]
Actually, it is quite easy for yourself to implement the m3u8.
You can read the m3u8 by in your code, find out the .TS URL and feed it to the thumbnail.

**Comment by rekonvald** [comment]
Thank you. Could you please provide an example

**Comment by justsoft** [comment]
Google is your friend:)

**Comment by rekonvald** [comment]
Thanks, solved problem with https://pub.dev/packages/m3u and extracting .ts from it

**Comment by rekonvald** [comment]
Hi!
I've tested .ts file on Android and it worked, but on IOS it doesn't
https://s3.eu-west-3.amazonaws.com/uat-call-video/records/483b8af08c49b51bfdb284bb2d55ace4_078f90b7-f1f1-4470-acae-e6956cc250e8_20210326111818788.ts

**Comment by justsoft** [comment]
Sorry, my MacBookPro has something wrong in this moment, can't help you now.
Please give this https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8 a try, try this URL without the m3u8 parser.

**Comment by Hwan-seok** [comment]
Thank you for maintaining a great plugin :)
When this will be implemented by internally?
