### ISSUE TITLE
 Unhandled Exception: MissingPluginException(No implementation found for method file on channel video_thumbnail)

### ISSUE THREAD

**Issue by nanian** [justsoft/video_thumbnail#65]
final uint8list = await VideoThumbnail.thumbnailFile(
          video: photoBean.path,
          imageFormat: ImageFormat.JPEG,
          // specify the width of the thumbnail, let the height auto-scaled to keep the source aspect ratio
          quality: 55,
        );
我用的video_thumbnail: ^0.3.1最新版，现在还是有这个问题老哥，能在修复下吗
E/wagnfei==(21391): {"imageList":[{"name":"VID_20210226_193823.mp4","path":"\/storage\/emulated\/0\/DCIM\/Camera\/VID_20210226_193823.mp4","type":"-1"},{"name":"1591193340707.mp4","path":"\/storage\/emulated\/0\/tencent\/MicroMsg\/WeiXin\/1591193340707.mp4","type":"-1"}]}
I/flutter (21391): resultImageState=/storage/emulated/0/DCIM/Camera/VID_20210226_193823.mp4
D/ThumbnailPlugin(21391): buildThumbnailFile( format:0, maxh:0, maxw:75, timeMs:0, quality:55 )
D/ThumbnailPlugin(21391): buildThumbnailData( format:0, maxh:0, maxw:75, timeMs:0, quality:55 )
D/ThumbnailPlugin(21391): original w:1080, h:1920 => 75, 133
E/flutter (21391): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method file on channel video_thumbnail)
E/flutter (21391): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (21391): <asynchronous suspension>
E/flutter (21391): #1      VideoThumbnail.thumbnailFile (package:video_thumbnail/video_thumbnail.dart:44:12)
E/flutter (21391): <asynchronous suspension>
E/flutter (21391): #2      _EvaluationWidgetState._pickAsset (package:flutter111/widget/EvaluationWidget.dart:421:27)
E/flutter (21391): <asynchronous suspension>
E/flutter (21391): 
QQ：390774562

**Comment by justsoft** [comment]
Please check the video is playable on your device.

**Comment by nanian** [comment]
视频是手机拍摄的，可以正常播放，拿到视频地址后获取不到第一帧






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justsoft/video_thumbnail"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 中午12:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [justsoft/video_thumbnail]  Unhandled Exception: MissingPluginException(No implementation found for method file on channel video_thumbnail) (#65)





 
Please check the video is playable on your device.

**Comment by nanian** [comment]
你那有没有图片和视频选择的例子，推荐一个给我吧我正在学习这块，谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justsoft/video_thumbnail"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 中午12:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [justsoft/video_thumbnail]  Unhandled Exception: MissingPluginException(No implementation found for method file on channel video_thumbnail) (#65)





 
Closed #65.

**Comment by nanian** [comment]
老哥：我的flutter还没升级2.0呢，没办法用0.3.1的版本，如果用之前的版本会不会有问题呢，能否兼容下2.0以下的版本，在线等






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "justsoft/video_thumbnail"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月25日(星期四) 中午12:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [justsoft/video_thumbnail]  Unhandled Exception: MissingPluginException(No implementation found for method file on channel video_thumbnail) (#65)





 
Please check the video is playable on your device.

**Comment by justsoft** [comment]
Please take a look my example.

**Comment by ForeverZhangXun** [comment]
I also encountered this problem. Finally, I found that it was due to the problem of quality setting. If I set the quality to 200, It would fail. If I set the quality to 100, It would success.
await VideoThumbnail.thumbnailFile(
      video: _videoPath,
      thumbnailPath: (await getTemporaryDirectory()).path,
      imageFormat: ImageFormat.JPEG,
      maxHeight: 1000,
      quality: 100,
    )

**Comment by justsoft** [comment]
Thanks for the finding, the `quality` should be 100 or less, it is the percentage of quality of the original image.
