### ISSUE TITLE
Support for Flutter Module

### ISSUE THREAD

**Issue by therealblue10** [justsoft/video_thumbnail#70]
Giving this error when integrated with Flutter Module

> The plugin `video_thumbnail` is built using an older version of the Android plugin API which assumes that it's running in a full-Flutter environment. It may have undefined behaviors when Flutter is integrated into an existing app as a module.
> The plugin can be updated to the v2 Android Plugin APIs by following https://flutter.dev/go/android-plugin-migration.

**Comment by justsoft** [comment]
Thanks for the suggestion, I will do this when I have more free time.
