### ISSUE TITLE
Sometimes unable to create thumbnails

### ISSUE THREAD

**Issue by nero-angela** [justsoft/video_thumbnail#71]
Thanks for making the package.

I am currently using the ^0.2.5+1 version, and I am making a silent camera.
I am working on extracting thumbnails from short videos taken with the [camera package](https://pub.dev/packages/camera). 4 out of 5 works fine, but sometimes I get an error saying that the thumbnail cannot be created.

**code**
```
await controller.startVideoRecording();
Future.delayed(Duration(milliseconds: 300), () async {
  final videoFile = await controller.stopVideoRecording();
  final image = VideoThumbnail.thumbnailData(video: videoFile.path);
});
```

**device info**
platform: iOS
device model: iPhone8
device version: 14.4.1

**screenshot**
<img width="950" alt="스크린샷 2021-04-17 오후 3 17 28" src="https://user-images.githubusercontent.com/26322627/115104830-fee07b00-9f95-11eb-82d0-21e9fa9703c8.png">

**Comment by justsoft** [comment]
Try something out:
1) Make sure the video is readable before call `thumbnailData`
2) Retry once `thumbnailData` failed
