### ISSUE TITLE
Not working for large video files

### ISSUE THREAD

**Issue by achinverma** [justsoft/video_thumbnail#76]
Hi , i am using this library to create a video thumbnail from video url. 

But my video thumbnails are not creating it for the large video files, like if the video size is 50 MB, i have tested it with the demo app video url, the size of the dummy video url is 3 mb and it works fine for me.

dummy video url: https://flutter.github.io/assets-for-api-docs/assets/videos/butterfly.mp4

this is the video url , which is not working with this lib:
https://s3.eu-central-1.amazonaws.com/appventure-prod-eu-central/videos/05862bd1-461c-4e2c-9f93-7a8b35c057c0.mp4

**Comment by achinverma** [comment]
@justsoft , Pls guide me

**Comment by achinverma** [comment]
@lqs , @jlavyan , @imhafeez . Pls anyone guide me to fix the issue.

**Comment by imtoori** [comment]
same here

**Comment by justsoft** [comment]
Testing.

**Comment by justsoft** [comment]
Looks like the `https://s3.eu-central-1.amazonaws.com/appventure-prod-eu-central/videos/05862bd1-461c-4e2c-9f93-7a8b35c057c0.mp4` isn't playable on my Android device.
Have you tried another files?

**Comment by achinverma** [comment]
> Looks like the `https://s3.eu-central-1.amazonaws.com/appventure-prod-eu-central/videos/05862bd1-461c-4e2c-9f93-7a8b35c057c0.mp4` isn't playable on my Android device.
> Have you tried another files?

may be, the video is deleted from our server. But you can try with any other large video files.
