### ISSUE TITLE
PlatformException(IO Error, Failed to write data to file, null, null)

### ISSUE THREAD

**Issue by EjazAmir** [justsoft/video_thumbnail#78]
getting this error on real devices.

PlatformException(IO Error, Failed to write data to file, null, null)

**Comment by vinothvino42** [comment]
I'm also getting the same exception in iOS
![Screenshot 2021-06-04 at 7 23 17 PM (2)](https://user-images.githubusercontent.com/12869588/120812377-8d22b780-c56a-11eb-8756-1b7c3f9c24bf.png)

**Comment by ChokShen** [comment]
I am using v0.3.3, but still sometimes getting this error.
PlatformException(IO Error, Failed to write data to file, null, null)

**Comment by justsoft** [comment]
Use the `thumbnailData` instead of wring into a file to see if it is permission issue.
