### ISSUE TITLE
Unhandled Exception when create thumbnail.

### ISSUE THREAD

**Issue by parth22** [justsoft/video_thumbnail#8]
i'm using 
video_thumbnail: ^0.1.7
```
E/flutter (15359): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method data on channel video_thumbnail)
E/flutter (15359): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter (15359): <asynchronous suspension>
E/flutter (15359): #1      VideoThumbnail.thumbnailData (package:video_thumbnail/video_thumbnail.dart:63:27)
```

**Comment by anil-sookshum** [comment]
Getting the same issue while building a  release build but working fine with debug build.

**Comment by justsoft** [comment]
Try to force the video_thumbnail version back to 0.1.6?
```
video_thumbnail: 0.1.6
```

**Comment by anil-sookshum** [comment]
Still not working. After downgrading version this is affecting my App performance also.

**Comment by harshapulikollu** [comment]
Facing the same issue, even downgraded the plugin version and tried. But resulted same error.
IDE- VS code 1.41.0
Flutter - master 1.13.3-pre.23
Dart - 2.8.0-dev.0.0

**Comment by justsoft** [comment]
I don't have an Android TV to test. Is it the API level too low?

**Comment by harshapulikollu** [comment]
But I'm facing this issue when I try to run the debug version of my app in android device, not on Android TV.

**Comment by justsoft** [comment]
The plugin works fine for me. Please try the example App, if it works then make a change for what you do in your App.

**Comment by justsoft** [comment]
Please try to play this video on your device, if it wouldn't be able to play, pretty high chance to get failure for generating the thumbnail.

**Comment by biklas7** [comment]
This is still happening on version 0.2.1

**Comment by justsoft** [comment]
@biklas7 Try to play the video in the device's browser and other media player to make sure your device has proper decoder.

**Comment by biklas7** [comment]
@justsoft It's really weird. I'm working on an app that shows a big list of media thumbnails, and sometimes the app throws this error for a specific media URL, especially when I scroll very fast, and sometimes it works.

**Comment by vikalpnagar** [comment]
I am also facing this issue on version 0.2.1

**Comment by vikalpnagar** [comment]
> Try to force the video_thumbnail version back to 0.1.6?
> 
> ```
> video_thumbnail: 0.1.6
> ```

Finally, downgrading worked.

**Comment by justsoft** [comment]
@vikalpnagar @biklas7 Before the downgrade, which platform had the issue, iOS or Android?
Did you URL encoded the URL?
Is the problematic URL playable by device's browser?
The plugin spawned a thread to generate the thumbnail instead of the main UI thread since version 0.1.7. Creating too many threads may cause the problem. Try to use a queue to control thumbnail generation.

**Comment by redvg** [comment]
downgrading to 0.1.6 removed the original issue, but gave another one   
<img width="1341" alt="4" src="https://user-images.githubusercontent.com/38582053/83716958-afb98200-a631-11ea-9a6a-fecca60fe17c.png">  

https://github.com/justsoft/video_thumbnail/issues/23  https://github.com/justsoft/video_thumbnail/issues/27
