### ISSUE TITLE
VideoThumbnailPlugin.java uses or overrides a  deprecated API

### ISSUE THREAD

**Issue by aenckli** [justsoft/video_thumbnail#81]
This errors come out when I build my project.

Note: D:\Program Files\flutter\.pub-cache\hosted\pub.dartlang.org\video_thumbnail-0.3.3\android\src\main\java\xyz\justsoft\video_thumbnail\VideoThumbnailPlugin.java uses or overrides a
 deprecated API.
Note: Recompile with -Xlint:deprecation for details.

Although I can continue to build, it still makes me worry about failure in certain situation. How can I solve this ?

**Comment by justsoft** [comment]
Please upgrade to the latest version to see if this warning still exists.

**Comment by aenckli** [comment]
the same after put ^0.4.3 in pubspec.yaml.

**Comment by syssam** [comment]
same issue, any update?

**Comment by aenckli** [comment]
The same issue.
I am not using null safety. Is this related?

**Comment by justsoft** [comment]
> The same issue.
> I am not using null safety. Is this related?

Not really.
Right now, please ignore this warning.
