### ISSUE TITLE
Get video thumbnail from icloud video file, occurs an error

### ISSUE THREAD

**Issue by mikeooye** [justsoft/video_thumbnail#87]
```dart
    String? thumbnailPath;
    var tmpPath = (await getTemporaryDirectory()).path;
    try {
      thumbnailPath = await VideoThumbnail.thumbnailFile(
          video: this.path,
          imageFormat: ImageFormat.PNG,
          maxHeight: 280,
          maxWidth: 280,
          quality: 9,
          thumbnailPath: tmpPath);
    } catch (e) {
      Log.e('$path, $tmpPath, $e');
    }
```

The video path is: `/private/var/mobile/Containers/Data/Application/D59FD25C-5C9B-4E71-9AE0-75E4A0793F69/tmp/cn.lanehub.talent-Inbox/乔治第一天上幼儿园.mp4`

<img width="1041" alt="截屏2021-10-15 14 59 24" src="https://user-images.githubusercontent.com/4506059/137445483-834f0f94-35a0-4cc6-86d8-9f29c5d72116.png">

**Comment by justsoft** [comment]
Check the write permission.
