### ISSUE TITLE
Package support to android TV

### ISSUE THREAD

**Issue by Athanax** [justsoft/video_thumbnail#9]
This error occurs when i run the application on an android TV but it runs well on android emulator

An Observatory debugger and profiler on sdk google atv x86 is available at: http://127.0.0.1:36955/Ftp9s7nHQ5I=/
For a more detailed help message, press "h". To detach, press "d"; to quit, press "q".
D/ThumbnailPlugin( 7154): buildThumbnailData( format:1, maxhow:0, timeMs:0, quality:25 )
D/ThumbnailPlugin( 7154): setDataSource: https://www.cinemaworldtheaters.com/trailers/hustlers.mp4 )
V/MediaHTTPService( 7154): MediaHTTPService(android.media.MediaHTTPService@bc060a0): Cookies: null
V/MediaHTTPService( 7154): makeHTTPConnection: CookieManager created: java.net.CookieManager@a1a1459
V/MediaHTTPService( 7154): makeHTTPConnection(android.media.MediaHTTPService@bc060a0): cookieHandler: java.net.CookieManager@a1a1459 Cookies: null
D/NetworkSecurityConfig( 7154): No Network Security Config specified, using platform default
I/mple.movies_ap( 7154): Waiting for a blocking GC ProfileSaver
I/mple.movies_ap( 7154): WaitForGcToComplete blocked ProfileSaver on HeapTrim for 69.143ms
W/System.err( 7154): java.lang.RuntimeException: setDataSource failed: status = 0x80000000
W/System.err( 7154): 	at android.media.MediaMetadataRetriever._setDataSource(Native Method)
W/System.err( 7154): 	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:102)
W/System.err( 7154): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.createVideoThumbnail(VideoThumbnailPlugin.java:201)
W/System.err( 7154): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.buildThumbnailData(VideoThumbnailPlugin.java:115)
W/System.err( 7154): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin.access$100(VideoThumbnailPlugin.java:37)
W/System.err( 7154): 	at xyz.justsoft.video_thumbnail.VideoThumbnailPlugin$1.run(VideoThumbnailPlugin.java:76)
W/System.err( 7154): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 7154): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 7154): 	at java.lang.Thread.run(Thread.java:764)
E/flutter ( 7154): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method data on channel video_thumbnail)
E/flutter ( 7154): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
E/flutter ( 7154): <asynchronous suspension>
E/flutter ( 7154): #1      VideoThumbnail.thumbnailData (package:video_thumbnail/video_thumbnail.dart:63:27)
E/flutter ( 7154): <asynchronous suspension>
E/flutter ( 7154): #2      _HomeState.getimage (package:movies_app/views/Home.dart:60:44)
E/flutter ( 7154): <asynchronous suspension>
E/flutter ( 7154): #3      _HomeState.build.<anonymous closure>.<anonymous closure> (package:movies_app/views/Home.dart:139:27)
E/flutter ( 7154): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
E/flutter ( 7154): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
E/flutter ( 7154): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 7154): #7      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
E/flutter ( 7154): #8      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:312:7)
E/flutter ( 7154): #9      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 7154): #10     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter ( 7154): #11     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 7154): #12     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 7154): #13     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 7154): #14     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 7154): #15     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter ( 7154): #16     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter ( 7154): #17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter ( 7154): #18     _invoke1 (dart:ui/hooks.dart:263:10)
E/flutter ( 7154): #19     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
E/flutter ( 7154):

**Comment by justsoft** [comment]
Please try following steps to confirm where the problem comes from:
1) Try to create thumbnails in memory from a local video
2) Try to create thumbnails in memory from http scheme URL
3) Try to create thumbnails in memory from https scheme URL
4) Try to save the thumbnails in App's folder
...
Apply some permissions and try again...
Let me know how thing goes.

**Comment by Athanax** [comment]
This is the link for the solution
https://github.com/justsoft/video_thumbnail/issues/10#issuecomment-565795883

**Comment by justsoft** [comment]
Thank you
